TFCEvents.data(e => {
  const materials = [
    "copper",
    "bronze",
    "bismuth_bronze",
    "black_bronze",
    "wrought_iron",
    "steel",
    "red_steel",
    "blue_steel",
    "black_steel"
  ];

  materials.forEach(material => {
    e.itemSize(`kubejs:${material}_battle_hammer`, 'large', 'heavy') // 大锤
    e.itemSize(`kubejs:${material}_warhammer`, 'large', 'medium') // 战锤
    e.itemSize(`kubejs:${material}_lance`, 'very_large', 'heavy') // 骑枪
    e.itemSize(`kubejs:${material}_flanged_mace`, 'large', 'heavy');        // 页锤
    e.itemSize(`kubejs:${material}_scythe`, 'very_large', 'heavy');             // 战镰
    e.itemSize(`kubejs:${material}_greatsword`, 'very_large', 'heavy');             // 大剑

    e.itemSize(`kubejs:${material}_halberd`, 'very_large', 'heavy');             // 戟

    e.itemSize(`kubejs:${material}_throwing_knife`, 'normal', 'light');      // 飞刀
    e.itemSize(`kubejs:${material}_dagger`, 'normal', 'light');              // 匕首
    e.itemSize(`kubejs:${material}_parrying_dagger`, 'normal', 'light');     // 格挡匕首


    e.itemSize(`kubejs:${material}_battle_hammer_weapon_part`, 'large', 'heavy') // 大锤部件
    e.itemSize(`kubejs:${material}_warhammer_weapon_part`, 'normal', 'medium') // 战锤部件
    e.itemSize(`kubejs:${material}_lance_weapon_part`, 'large', 'heavy') // 骑枪部件
    e.itemSize(`kubejs:${material}_flanged_mace_weapon_part`, 'normal', 'medium');        // 页锤部件
    e.itemSize(`kubejs:${material}_scythe_weapon_part`, 'large', 'heavy');             // 战镰部件
    e.itemSize(`kubejs:${material}_greatsword_weapon_part`, 'large', 'heavy');             // 大剑部件
    e.itemSize(`kubejs:${material}_halberd_weapon_part`, 'large', 'heavy');             // 戟部件
  });


  const small_light_items = [  //小、轻
    '#kubejs:8ore',
    'kubejs:silicon',
    'kubejs:leather_plate',
    'kubejs:leather_scales',
    'kubejs:leather_scraps',
    'kubejs:silicon_board',
    'kubejs:obsidian_shards',
    'wildfire:snake',
    'wildfire:cooked_snake',
    'wildfire:thick_meat',
    'wildfire:cooked_thick_meat',
    'wildfire:cooked_red_mushroom',
    'wildfire:cooked_brown_mushroom',
    'wildfire:rat',
    'wildfire:baked_maize',
    'wildfire:baked_red_pepper',
    'wildfire:baked_yellow_bell_pepper',
    'wildfire:baked_green_pepper',
    'wildfire:baked_garlic',
    'wildfire:baked_red_apple',
    'wildfire:baked_green_apple',
    'wildfire:baked_carrot',
    'wildfire:pumpkin_dough',
    'wildfire:pumpkin_bread',
    'wildfire:pumpkin_bread_slice',
    'wildfire:cooked_rat'
  ]
  small_light_items.forEach(item => {
    e.itemSize(item, 'small', 'light')
  })



  const small_very_light_items = [  //小、非常轻
    '#tfc:seeds'
  ]
  small_very_light_items.forEach(item => {
    e.itemSize(item, 'small', 'very_light')
  })

  //实心金属块

  const large_very_heavy_items = [  //大、非常重
    "moreburners:electric_burner",
    "immersiveengineering:coil_lv",
    "immersiveengineering:coil_mv",
    "immersiveengineering:coil_hv",
    "create:zinc_block",
    "minecraft:iron_block",
    "minecraft:gold_block",
    "minecraft:copper_block",
    "create:brass_block",
    "immersiveengineering:storage_electrum",
    "immersiveengineering:storage_silver",
    "immersiveengineering:storage_nickel",
    "immersiveengineering:storage_lead",
    "immersiveengineering:storage_aluminum",
    "immersiveengineering:storage_steel",
    "immersiveengineering:storage_constantan",
    "create:andesite_alloy_block",
    "minecraft:cut_copper",
    "minecraft:cut_copper_stairs",
    "minecraft:cut_copper_slab",
    "minecraft:exposed_copper",
    "minecraft:exposed_cut_copper",
    "minecraft:oxidized_cut_copper_stairs",
    "minecraft:oxidized_cut_copper",
    "minecraft:oxidized_copper",
    "minecraft:weathered_cut_copper_slab",
    "minecraft:weathered_cut_copper_stairs",
    "minecraft:weathered_cut_copper",
    "minecraft:weathered_copper",
    "minecraft:exposed_cut_copper_stairs",
    "minecraft:exposed_cut_copper_slab",
    "minecraft:exposed_oxidized_cut_copper_slab",
    "minecraft:waxed_copper_block",
    "minecraft:waxed_cut_copper",
    "minecraft:waxed_cut_copper_stairs",
    "minecraft:waxed_cut_copper_slab",
    "minecraft:waxed_exposed_copper",
    "minecraft:waxed_exposed_cut_copper",
    "minecraft:waxed_exposed_cut_copper_stairs",
    "minecraft:waxed_exposed_cut_copper_slab",
    "minecraft:waxed_oxidized_cut_copper_slab",
    "minecraft:waxed_oxidized_cut_copper_stairs",
    "minecraft:waxed_oxidized_cut_copper",
    "minecraft:waxed_oxidized_copper",
    "minecraft:waxed_weathered_cut_copper_slab",
    "minecraft:waxed_weathered_cut_copper_stairs",
    "minecraft:waxed_weathered_cut_copper",
    "minecraft:waxed_weathered_copper",
    "wildfires:biplane_engine",
    "wildfires:large_airship_engine",
    "wildfires:rugged_small_engine",
    "wildfires:small_engine",
    "wildfires:small_side_engine",
    "wildfires:submarine_core",
    "wildfires:underwater_turbine"
  ]
  large_very_heavy_items.forEach(item => {
    e.itemSize(item, 'large', 'very_heavy')
  })


  const huge_very_heavy_items = [  //极大、非常重
    "immersive_aircraft:phull",
    "immersive_aircraft:engine",
    "immersive_aircraft:boiler",
    "immersive_aircraft:airship",
    "immersive_aircraft:cargo_airship",
    "immersive_aircraft:warship",
    "immersive_aircraft:biplane",
    "immersive_aircraft:gyrodyne",
    "immersive_aircraft:quadrocopter",
    "immersive_aircraft:rotary_cannon",
    "immersive_aircraft:heavy_crossbow",
    "immersive_aircraft:telescope",
    "immersive_aircraft:bomb_bay",
    "immersive_aircraft:enhanced_propeller",
    "immersive_aircraft:eco_engine",
    "immersive_aircraft:nether_engine",
    "immersive_aircraft:steel_boiler",
    "immersive_aircraft:hull_reinforcement",
    "siegemachines:mortar",
    "siegemachines:culverin",
    "siegemachines:catapult",
    "siegemachines:trebuchet",
    "siegemachines:ballista",
    "siegemachines:battering_ram",
    "siegemachines:siege_ladder",
    "siegemachines:cannonball",
    "siegemachines:barrel",
    "ad_astra:tier_3_rocket",
    "ad_astra:tier_2_rocket",
    "ad_astra:tier_1_rocket",
    "ad_astra:tier_4_rocket",
    "ad_astra:tier_1_rover",
    "siegemachines:counterweight",
    "trotting_wagons:armored_wagon",
    "trotting_wagons:conestoga_wagon",
    "trotting_wagons:royal_wagon",
    "simplytents:zip_tent",
    "simplytents:roof_tent",
    "simplytents:wall_tent",
    "simplytents:tent",
    "simplytents:canvas_wall"
  ]
  huge_very_heavy_items.forEach(item => {
    e.itemSize(item, 'huge', 'very_heavy')
  })

  //非常大、中
  const very_large_medium_items = [
    "kubejs:wood_briquette",
    "kubejs:charcoal_briquette",
    "kubejs:coal_briquette",
    "kubejs:coke_briquette",
    "kubejs:high_performance_briquette",
    "kubejs:cast_iron_indenter",
    "kubejs:emergency_hammer"
  ]
  very_large_medium_items.forEach(item => {
    e.itemSize(item, 'very_large', 'medium')
  })



  const large_heavy_items = [  //大、重
    "#kubejs:triple_ingot",
    "siegemachines:turret_base",
    "siegemachines:beam",
    "siegemachines:giant_arrow",
    "#tfc:sluices",
    "irons_spellbooks:archevoker_helmet",
    "irons_spellbooks:cultist_helmet",
    "irons_spellbooks:cultist_leggings",
    "irons_spellbooks:cultist_chestplate",
    "irons_spellbooks:cultist_boots",
    "irons_spellbooks:priest_leggings",
    "irons_spellbooks:electromancer_leggings",
    "irons_spellbooks:electromancer_chestplate",
    "irons_spellbooks:electromancer_boots",
    "immersiveengineering:armor_faraday_helmet",
    "immersiveengineering:armor_faraday_chestplate",
    "minecraft:chainmail_boots",
    "minecraft:chainmail_leggings",
    "minecraft:chainmail_chestplate",
    "minecraft:chainmail_helmet",
    "irons_spellbooks:pyromancer_helmet",
    "irons_spellbooks:pumpkin_boots",
    "irons_spellbooks:pumpkin_leggings",
    "irons_spellbooks:pumpkin_chestplate",
    "irons_spellbooks:pumpkin_helmet",
    "irons_spellbooks:cryomancer_helmet",
    "irons_spellbooks:priest_helmet",
    "irons_spellbooks:priest_boots",
    "irons_spellbooks:pyromancer_boots",
    "irons_spellbooks:pyromancer_chestplate",
    "irons_spellbooks:pyromancer_leggings",
    "irons_spellbooks:shadowwalker_chestplate",
    "irons_spellbooks:shadowwalker_helmet",
    "irons_spellbooks:shadowwalker_boots",
    "irons_spellbooks:archevoker_chestplate",
    "irons_spellbooks:cryomancer_boots",
    "irons_spellbooks:cryomancer_chestplate",
    "irons_spellbooks:cryomancer_leggings",
    "irons_spellbooks:priest_chestplate",
    "irons_spellbooks:electromancer_helmet",
    "irons_spellbooks:archevoker_leggings",
    "tfc:metal/boots/bismuth_bronze",
    "tfc:metal/chestplate/bismuth_bronze",
    "tfc:metal/helmet/bismuth_bronze",
    "warriorsofpastepoch:muketers_armor_chestplate",
    "warriorsofpastepoch:muketers_armor_helmet",
    "alexsmobs:spiked_turtle_shell",
    "alexsmobs:centipede_leggings",
    "alexsmobs:crocodile_chestplate",
    "warriorsofpastepoch:muketers_armor_leggings",
    "warriorsofpastepoch:muketers_armor_boots",
    "warriorsofpastepoch:plague_doctor_armor_helmet",
    "warriorsofpastepoch:plague_doctor_armor_chestplate",
    "warriorsofpastepoch:plague_doctor_armor_leggings",
    "warriorsofpastepoch:plague_doctor_armor_boots",
    "tfc:metal/helmet/bronze",
    "tfc:metal/boots/black_bronze",
    "tfc:metal/greaves/black_bronze",
    "tfc:metal/chestplate/black_bronze",
    "tfc:metal/helmet/black_bronze",
    "tfc:metal/greaves/bismuth_bronze",
    "immersiveengineering:armor_faraday_leggings",
    "immersiveengineering:armor_faraday_boots",
    "tfc:metal/boots/copper",
    "kaleidoscope_tavern:barrel"
  ]

  large_heavy_items.forEach(item => {
    e.itemSize(item, 'large', 'heavy')
  })


  const large_medium_items = [  //大,中
    '#kubejs:16ore',
    '#kubejs:tongs',
    "kubejs:wrought_iron_crowbar",
    "kubejs:steel_crowbar",
    "kubejs:black_steel_crowbar",
    "kubejs:cervelliere",
    "kubejs:leather_gamberson",
    "kubejs:leather_plate_greaves",
    "kubejs:leather_plate_boots",

    "tfc:ore/rich_cassiterite",
    "tfc:ore/rich_native_silver",
    "tfc:ore/rich_hematite",
    "tfc:ore/rich_native_gold",
    "tfc:ore/rich_native_copper",
    "tfc_ie_addon:ore/rich_uraninite",
    "tfc_ie_addon:ore/rich_galena",
    "tfc_ie_addon:ore/rich_bauxite",
    "firmalife:ore/rich_chromite",
    "tfc:ore/rich_bismuthinite",
    "tfc:ore/rich_garnierite",
    "tfc:ore/rich_malachite",
    "tfc:ore/rich_magnetite",
    "tfc:ore/rich_limonite",
    "tfc:ore/rich_sphalerite",
    "tfc:ore/rich_tetrahedrite",
    "textile:sabertooth_hat",
    "textile:direwolf_boots",
    "textile:direwolf_pants",
    "textile:direwolf_shirt",
    "textile:direwolf_hat",
    "farmlife:beekeeper_boots",
    "farmlife:beekeeper_chestplate",
    "farmlife:beekeeper_leggings",
    "farmlife:beekeeper_helmet",
    "irons_spellbooks:wandering_magician_leggings",
    "irons_spellbooks:wandering_magician_chestplate",
    "irons_spellbooks:wandering_magician_helmet",
    "legendarysurvivaloverhaul:desert_leggings",
    "legendarysurvivaloverhaul:desert_chestplate",
    "legendarysurvivaloverhaul:desert_helmet",
    "legendarysurvivaloverhaul:desert_boots",
    "eidolon:warlock_boots",
    "eidolon:warlock_cloak",
    "eidolon:warlock_hat",
    "irons_spellbooks:shadowwalker_leggings",
    "textile:polar_bear_hat",
    "textile:polar_bear_shirt",
    "textile:polar_bear_pants",
    "textile:polar_bear_boots",
    "alexscaves:primordial_tunic",
    "alexscaves:primordial_pants",
    "textile:cougar_hat",
    "textile:cougar_shirt",
    "textile:cougar_pants",
    "textile:cougar_boots",
    "textile:sabertooth_boots",
    "textile:sabertooth_pants",
    "textile:sabertooth_shirt",
    "textile:lion_boots",
    "textile:lion_pants",
    "textile:lion_shirt",
    "textile:lion_hat",
    "textile:grizzly_bear_boots",
    "textile:grizzly_bear_pants",
    "textile:grizzly_bear_shirt",
    "textile:grizzly_bear_hat",
    "irons_spellbooks:wandering_magician_boots",
    "alexscaves:cloak_of_darkness",
    "alexscaves:hood_of_darkness",
    "textile:crocodile_boots",
    "textile:crocodile_pants",
    "textile:crocodile_hat",
    "textile:crocodile_shirt",
    "irons_spellbooks:archevoker_boots",
    "textile:caribou_boots",
    "textile:caribou_pants",
    "textile:caribou_shirt",
    "textile:caribou_hat",
    "legendarysurvivaloverhaul:snow_boots",
    "minecraft:leather_boots",
    "textile:tiger_hat",
    "textile:tiger_shirt",
    "textile:tiger_pants",
    "textile:tiger_boots",
    "textile:panther_hat",
    "textile:panther_shirt",
    "textile:panther_pants",
    "textile:panther_boots",
    "legendarysurvivaloverhaul:snow_chestplate",
    "legendarysurvivaloverhaul:snow_helmet",
    "legendarysurvivaloverhaul:snow_leggings",
    "minecraft:leather_leggings",
    "minecraft:leather_helmet",
    "minecraft:leather_chestplate",
    "textile:black_bear_boots",
    "endermanoverhaul:snowy_hood",
    "endermanoverhaul:savanna_hood",
    "endermanoverhaul:badlands_hood",
    "alexsmobs:roadrunner_boots",
    "alexsmobs:emu_leggings",
    "alexscaves:hazmat_boots",
    "alexscaves:hazmat_mask",
    "alexscaves:hazmat_chestplate",
    "alexscaves:hazmat_leggings",
    "textile:black_bear_hat",
    "textile:black_bear_shirt",
    "textile:black_bear_pants",
    "create:mechanical_harvester",
    "create:controls",
    "create:item_drain",
    "create:nozzle",
    "create:item_hatch",
    "create:stock_link",
    "create:stock_ticker",
    "copycats:copycat_fluid_pipe",
    "copycats:copycat_large_cogwheel",
    "create:sail_frame",
    "create:white_sail",
    "create:item_vault",
    "create:blaze_burner",
    "create:chute",
    "create:fluid_valve",
    "create:fluid_pipe",
    "create:piston_extension_pole",
    "create:water_wheel",
    "create:smart_chute",
    "create:smart_fluid_pipe",
    "create:content_observer",
    "create:mechanical_arm",
    "create:contraption_controls",
    "create:flywheel",
    "create:large_cogwheel",
    "create:stockpile_switch",
    "create:andesite_funnel",
    "create:andesite_tunnel",
    "create:repackager",
    "create:basin",
    "create:stressometer",
    "create:weighted_ejector",
    "create:packager",
    "create:mechanical_plough",
    "create:mechanical_piston",
    "create:mechanical_pump",
    "create_connected:large_crank_wheel",
    "create_connected:parallel_gearbox",
    "create_connected:inverted_clutch",
    "create_connected:inverted_gearshift",
    "create_connected:six_way_gearbox",
    "create:encased_fan",
    "create:sticky_mechanical_piston",
    "create:brass_tunnel",
    "create:brass_funnel",
    "petrolsparts:pneumatic_tube",
    "petrolsparts:differential",
    "petrolsparts:large_coaxial_gear",
    "petrolsparts:planetary_gearset",
    "createutilities:void_motor",
    "createutilities:gearcube",
    "createutilities:lshaped_gearbox",
    "create:display_board",
    "create:millstone",
    "create_power_loader:brass_chunk_loader",
    "create_power_loader:empty_brass_chunk_loader",
    "create_power_loader:empty_andesite_chunk_loader",
    "create_connected:encased_chain_cogwheel",  // 已修复
    "create_connected:fan_blasting_catalyst",
    "create_connected:fan_splashing_catalyst",
    "create_connected:fan_smoking_catalyst",
    "create_connected:fan_haunting_catalyst",
    "create_hypertube:hypertube_entrance",
    "create_new_age:basic_motor_extension",
    "create_new_age:advanced_motor_extension",
    "create_new_age:stirling_engine",
    "create_new_age:heat_pump",
    "create_new_age:heat_pipe",
    "create_power_loader:andesite_chunk_loader",
    "create_connected:vertical_parallel_gearbox",
    "create_connected:vertical_six_way_gearbox",
    "create_connected:empty_fan_catalyst",
    "create:speedometer",
    "create:gantry_shaft",
    "create:package_frogport",
    "create:depot",
    "create:redstone_requester",
    "create:empty_blaze_burner",
    "create:copper_valve_handle",
    "immersiveengineering:sawblade",
    "create:extendo_grip",
    "create:potato_cannon",
    "create:wand_of_symmetry",
    "createdieselgenerators:chemical_sprayer_lighter",
    "createdieselgenerators:chemical_sprayer",
    "kubejs:rusty_ancient_steel_scrap",
    "kubejs:ancient_steel_scrap",
    "kubejs:iron_scrap",
    "kubejs:copper_scrap",
    "kubejs:rusty_copper_scrap",
    "kubejs:rusty_bronze_scrap",
    "kubejs:bronze_scrap",
    "kubejs:rusty_iron_scrap",
    "createmetallurgy:foundry_basin",
    "createmetallurgy:casting_basin",
    "createmetallurgy:casting_table",
    "createmetallurgy:foundry_lid",
    "createmetallurgy:foundry_mixer",
    "createmetallurgy:faucet",
    "tfcgroomer:bismuth_bronze_grooming_station",
    "tfcgroomer:black_bronze_grooming_station",
    "tfcgroomer:bronze_grooming_station",
    "tfcgroomer:copper_grooming_station",
    "tfcgroomer:wrought_iron_grooming_station",
    "tfcgroomer:steel_grooming_station",
    "tfcgroomer:black_steel_grooming_station",
    "tfcgroomer:blue_steel_grooming_station",
    "tfcgroomer:red_steel_grooming_station",
    "create:brass_encased_large_cogwheel",
    "create:secondary_linear_chassis",
    "create:radial_chassis",
    "create:encased_chain_drive",
    "create:gearshift",
    "create:clutch",
    "create:windmill_bearing",
    "create:rope_pulley",
    "immersiveengineering:reinforced_crate",
    "create_connected:sequenced_pulse_generator",
    "create_enchantment_industry:printer",
    "create_enchantment_industry:disenchanter",
    "createdieselgenerators:pumpjack_hole",
    "create:andesite_encased_shaft",
    "create:brass_encased_shaft",
    "create:andesite_encased_cogwheel",
    "create_connected:brake",
    "create:andesite_encased_large_cogwheel",
    "create:brass_encased_cogwheel",
    "create:mechanical_crafter",
    "create:gearbox",
    "create:vertical_gearbox",
    "create:adjustable_chain_gearshift",
    "create:linear_chassis",
    "create:elevator_contact",
    "create:mysterious_cuckoo_clock",
    "create:sequenced_gearshift",
    "create_connected:kinetic_battery",
    "create_connected:charged_kinetic_battery",
    "create_connected:freewheel_clutch",
    "create_connected:centrifugal_clutch",
    "create_connected:overstress_clutch",
    "create_connected:vertical_brass_gearbox",
    "create_connected:brass_gearbox",
    "create_connected:large_crank_wheel",
    "immersiveengineering:redstone_breaker",
    "immersiveengineering:current_transformer",
    "immersiveengineering:connector_redstone",
    "immersiveengineering:connector_probe",
    "immersiveengineering:connector_bundled",
    "create_connected:fan_sanding_catalyst",
    "create_connected:fan_seething_catalyst",
    "create_connected:fan_freezing_catalyst",
    "create_connected:brass_encased_cross_connector",
    "immersiveengineering:furnace_heater",
    "immersiveengineering:dynamo",
    "immersiveengineering:fluid_placer",
    "immersiveengineering:heavy_engineering",
    "immersiveengineering:light_engineering",
    "immersiveengineering:generator",
    "immersiveengineering:light_engineering",
    "immersiveengineering:electromagnet",
    "immersiveengineering:thermoelectric_generator",
    "immersiveengineering:metal_barrel",
    "immersiveengineering:capacitor_lv",
    "immersiveengineering:capacitor_hv",
    "immersiveengineering:treated_wallmount",
    "immersiveengineering:watermill",
    "immersiveengineering:windmill",
    "immersiveengineering:craftingtable",
    "immersiveengineering:workbench",
    "immersiveengineering:circuit_table",
    "immersiveengineering:gunkpowder_barrel",
    "immersiveengineering:fluid_sorter",
    "immersiveengineering:capacitor_mv",
    "immersiveengineering:wooden_barrel",
    "immersiveengineering:item_batcher",
    "irons_spellbooks:alchemist_cauldron",
    "immersiveengineering:turntable",
    "immersiveengineering:sorter",
    "immersiveengineering:breaker_switch",
    "create_connected:andesite_encased_cross_connector",
  ]
  large_medium_items.forEach(item => {
    e.itemSize(item, 'large', 'medium')

  })

  const very_large_heavy_items = [  //非常大,重

    "create:track_station",
    "create:mechanical_press",
    "create:mechanical_roller",
    "create:mechanical_mixer",
    "create:mechanical_drill",
    "create:mechanical_saw",
    "create:large_water_wheel",
    "create:redstone_contact",
    "create:deployer",
    "create_connected:creative_fluid_vessel",
    "create_connected:kinetic_bridge",
    "create_connected:kinetic_battery",
    "create_connected:inventory_access_port",
    "create_connected:inventory_bridge",
    "create_connected:charged_kinetic_battery",
    "create_connected:fluid_vessel",
    "create_connected:item_silo",
    "create_new_age:netherite_magnet",
    "create_new_age:basic_solar_heating_plate",
    "create_new_age:energiser_t3",
    "create_new_age:reinforced_motor",
    "create:flywheel",
    "create:chain_conveyor",
    "create:hose_pulley",
    "create:rotation_speed_controller",
    "create:schematicannon",
    "create:steam_whistle",
    "create:steam_engine",
    "create:crushing_wheel",
    "create:portable_fluid_interface",
    "create:portable_storage_interface",
    "create:fluid_tank",
    "create:spout",
    "create:item_drain",
    "create:track_observer",
    "create:track_signal",
    "create_new_age:magnetite_block",
    "create_new_age:redstone_magnet",
    "create_new_age:fluxuated_magnetite",
    "create_new_age:layered_magnet",
    "create_new_age:heater",
    "create_new_age:advanced_solar_heating_plate",
    "create_new_age:energiser_t2",
    "create_new_age:advanced_motor",
    "createdieselgenerators:bulk_fermenter",
    "firmaciv:cannon",
    "firmaciv:cannon_barrel",
    "firmaciv:anchor",
    "immersiveengineering:chemthrower",
    "immersiveengineering:toolbox",
    "immersiveengineering:railgun",
    "immersiveengineering:drill",
    "minecraft:beacon",
    "minecraft:stonecutter",
    "minecraft:chipped_anvil",
    "minecraft:damaged_anvil",
    "minecraft:anvil",
    "firmaciv:anchor",
    "createutilities:void_battery",
    "createutilities:void_chest",
    "createutilities:void_tank",
    "createdieselgenerators:large_diesel_engine",
    "createdieselgenerators:diesel_engine",
    "createdieselgenerators:pumpjack_bearing",
    "createdieselgenerators:pumpjack_crank",
    "createdieselgenerators:canister",
    "createdieselgenerators:oil_barrel",
    "createdieselgenerators:chemical_turret",
    "createdieselgenerators:burner",
    "create_new_age:energiser_t1",
    "create_new_age:basic_motor",
    "create_new_age:carbon_brushes",
    "tfc:handstone",
    "tfce:refrigerator",
    "tfcoreprocessing:blue_steel_handstone",
    "tfcoreprocessing:black_steel_handstone",
    "tfcoreprocessing:red_steel_handstone",
    "tfcoreprocessing:steel_handstone",
    "tfcoreprocessing:cast_iron_handstone",
    "tfcoreprocessing:wrought_iron_handstone",
    "vintageimprovements:v_shaped_curving_head",
    "vintageimprovements:w_shaped_curving_head",
    "vintageimprovements:lathe",
    "vintageimprovements:centrifuge",
    "vintageimprovements:belt_grinder",
    "vintageimprovements:laser",
    "vintageimprovements:vibrating_table",
    "vintageimprovements:vacuum_chamber",
    "vintageimprovements:spring_coiling_machine",
    "vintageimprovements:concave_curving_head",
    "vintageimprovements:convex_curving_head",
    "vintageimprovements:curving_press",
    "moreburners:electric_burner",
    "petrolsparts:colossal_cogwheel",
    "petrolsparts:hydraulic_transmission",
    "immersiveengineering:crate",
    "create:brown_toolbox",
    "create:white_toolbox",
    "create:orange_toolbox",
    "create:magenta_toolbox",
    "create:light_blue_toolbox",
    "create:yellow_toolbox",
    "create:lime_toolbox",
    "create:pink_toolbox",
    "create:gray_toolbox",
    "create:light_gray_toolbox",
    "create:cyan_toolbox",
    "create:purple_toolbox",
    "create:blue_toolbox",
    "create:green_toolbox",
    "create:red_toolbox",
    "create:black_toolbox",
    "kubejs:explorer_cabin",
    "kubejs:flare_plating",
    "kubejs:hologram_frontpanel",
    "kubejs:moon_crystal_panel",
    "kubejs:moon_propeller",
    "kubejs:basic_cabin",
    "kubejs:advanced_plating",
    "kubejs:advanced_cabin",
    "kubejs:columbus_propeller",
    "kubejs:basic_propeller",
    "kubejs:basic_plating",
    "kubejs:basic_crystal_pannel",
    "kubejs:venus_plating",
    "immersiveengineering:transformer_hv",
    "immersiveengineering:transformer",
    "immersiveengineering:fluid_pump",
    "immersiveengineering:blastfurnace_preheater",
    "immersiveengineering:sample_drill",
    "immersiveengineering:turret_chem",
    "immersiveengineering:cloche",
    "immersiveengineering:turret_gun",
    "#forge:corpseitem",
    "sophisticatedbackpacks:backpack",
    "sophisticatedbackpacks:copper_backpack",
    "sophisticatedbackpacks:iron_backpack",
    "sophisticatedbackpacks:gold_backpack",
    "sophisticatedbackpacks:diamond_backpack",
    "sophisticatedbackpacks:netherite_backpack",
    "rubberworks:sapper"
  ]
  very_large_heavy_items.forEach(item => {
    e.itemSize(item, 'very_large', 'heavy')

  })
  
  const very_large_very_heavy_items = [//非常大、非常重
    "alexscaves:diving_boots",
    "alexscaves:diving_leggings",
    "alexscaves:diving_chestplate",
    "alexscaves:diving_helmet",
    "vintageimprovements:helve_hammer",
    "create:mechanical_bearing",
    "create:clockwork_bearing",
    "create:cart_assembler",
    "create:sticker",
    "create:gantry_carriage",
    "create_new_age:generator_coil",
    "createdieselgenerators:huge_diesel_engine"

  ]
  very_large_very_heavy_items.forEach(item => {
    e.itemSize(item, 'very_large', 'very_heavy')
  })

  //梁
  const support_items = ["kubejs:copper_support",
    "kubejs:bismuth_bronze_support",
    "kubejs:black_bronze_support",
    "kubejs:bronze_support",
    "kubejs:wrought_iron_support",
    "kubejs:steel_support",
    "kubejs:black_steel_support",
    "kubejs:red_steel_support",
    "kubejs:blue_steel_support",
    "kubejs:cast_iron_support",
    "kubejs:galvanized_steel_support"]
  support_items.forEach(item => {
    e.itemSize(item, 'large', 'Light')
  })

  
  const small_heavy_items = [//小、重
    'farmersdelight:ham',
    'farmersdelight:smoked_ham',
    "#tfc:jars",
  ]
  small_heavy_items.forEach(item => {
    e.itemSize(item, 'small', 'heavy')
  })

  const large_light_items = [ //大、轻
    "create:copper_shingles",
    "create:exposed_copper_shingles",
    "create:weathered_copper_shingles",
    "create:oxidized_copper_shingles",
    "create:copper_shingle_slab",
    "create:exposed_copper_shingle_slab",
    "create:weathered_copper_shingle_slab",
    "create:oxidized_copper_shingle_slab",
    "create:copper_shingle_stairs",
    "create:exposed_copper_shingle_stairs",
    "create:weathered_copper_shingle_stairs",
    "create:oxidized_copper_shingle_stairs",
    "create:waxed_copper_shingles",
    "create:waxed_exposed_copper_shingles",
    "create:waxed_weathered_copper_shingles",
    "create:waxed_oxidized_copper_shingles",
    "create:waxed_copper_shingle_slab",
    "create:waxed_exposed_copper_shingle_slab",
    "create:waxed_weathered_copper_shingle_slab",
    "create:waxed_oxidized_copper_shingle_slab",
    "create:waxed_copper_shingle_stairs",
    "create:waxed_exposed_copper_shingle_stairs",
    "create:waxed_weathered_copper_shingle_stairs",
    "create:waxed_oxidized_copper_shingle_stairs",
    "create:copper_tiles",
    "create:exposed_copper_tiles",
    "create:weathered_copper_tiles",
    "create:oxidized_copper_tiles",
    "create:copper_tile_slab",
    "create:exposed_copper_tile_slab",
    "create:weathered_copper_tile_slab",
    "create:oxidized_copper_tile_slab",
    "create:copper_tile_stairs",
    "create:exposed_copper_tile_stairs",
    "create:weathered_copper_tile_stairs",
    "create:oxidized_copper_tile_stairs",
    "create:waxed_copper_tiles",
    "create:waxed_exposed_copper_tiles",
    "create:waxed_weathered_copper_tiles",
    "create:waxed_oxidized_copper_tiles",
    "create:waxed_copper_tile_slab",
    "create:waxed_exposed_copper_tile_slab",
    "create:waxed_weathered_copper_tile_slab",
    "create:waxed_oxidized_copper_tile_slab",
    "create:waxed_copper_tile_stairs",
    "create:waxed_exposed_copper_tile_stairs",
    "create:waxed_weathered_copper_tile_stairs",
    "create:waxed_oxidized_copper_tile_stairs",
    "#tfc:looms",
    "#tfc:tool_racks",
    "create:cardboard_leggings",
    "create:cardboard_helmet",
    "alexsmobs:novelty_hat",
    "alexsmobs:sombrero",
    "call_of_yucutan:warrior_helmet",
    "call_of_yucutan:huracan_helmet",
    "alexsmobs:fedora",
    "alexsmobs:flying_fish_boots",
    "totemic:jingle_dress",
    "born_in_chaos_v1:missionary_hat_helmet",
    "born_in_chaos_v1:lord_pumpkinheads_hat_helmet",
    "born_in_chaos_v1:damned_demomans_hat_helmet",
    "born_in_chaos_v1:spiritual_guide_sombrero_helmet",
    "textile:silk_hat",
    "textile:silk_shirt",
    "textile:silk_pants",
    "textile:linen_hat",
    "textile:linen_shirt",
    "textile:linen_pants",
    "brewery:brewfest_blouse",
    "majruszsdifficulty:tattered_boots",
    "geckojs:artist_beret",
    "geckojs:elvish_ears",
    "geckojs:fungus_cape",
    "eidolon:top_hat",
    "alexsmobs:unsettling_kimono",
    "textile:burlap_pants",
    "textile:burlap_shirt",
    "textile:burlap_hat",
    "vinery:winemaker_boots",
    "vinery:winemaker_leggings",
    "vinery:winemaker_apron",
    "create:cardboard_boots",
    "create:cardboard_chestplate",
    "alexsmobs:frontier_cap",
    "alexsmobs:moose_headgear",
    "alexscaves:rainbounce_boots",
    "brewery:brewfest_trousers",
    "brewery:brewfest_dress",
    "brewery:brewfest_boots",
    "brewery:brewfest_shoes",
    "vinery:straw_hat",
    "majruszsdifficulty:tattered_chestplate",
    "majruszsdifficulty:tattered_helmet",
    "majruszsdifficulty:tattered_leggings",
    "brewery:brewfest_hat_red",
    "brewery:brewfest_hat",
    "brewery:brewfest_regalia",
    "rubberworks:compressor"

  ]
  large_light_items.forEach(item => {
    e.itemSize(item, 'large', 'light')
  })



  const normal_medium_items = [  //正常、中等
    'brewinandchewin:tankard',
    'brewinandchewin:beer',
    'brewinandchewin:vodka',
    'brewinandchewin:mead',
    'brewinandchewin:rice_wine',
    'brewinandchewin:pale_jane',
    'brewinandchewin:egg_grog',
    'brewinandchewin:glittering_grenadine',
    'brewinandchewin:saccharine_rum',
    'brewinandchewin:salty_folly',
    'brewinandchewin:bloody_mary',
    'brewinandchewin:red_rum',
    'brewinandchewin:strongroot_ale',
    'brewinandchewin:steel_toe_stout',
    'brewinandchewin:dread_nog',
    'brewinandchewin:withering_dross',
    'brewinandchewin:kombucha',
    'wildfire:beer_maize',
    'wildfire:beer_barley',
    'wildfire:beer_hops',
    'wildfire:beer_rye',
    'wildfire:beer_oat',
    'wildfire:beer_berries',
    'kaleidoscope_tavern:molotov',
    'kaleidoscope_tavern:vinegar',
    'kaleidoscope_tavern:wine',
    'kaleidoscope_tavern:ice_wine',
    'kaleidoscope_tavern:sakura_wine',
    'kaleidoscope_tavern:plum_wine',
    'kaleidoscope_tavern:champagne',
    'kaleidoscope_tavern:vodka',
    'kaleidoscope_tavern:brandy',
    'kaleidoscope_tavern:carignan',
    'kaleidoscope_tavern:whiskey',
    'kaleidoscope_tavern:trellis',
    'kaleidoscope_tavern:empty_bottle',
    'kaleidoscope_tavern:tap'
  ]
  normal_medium_items.forEach(item => {
    e.itemSize(item, 'normal', 'medium')
  })





})
