name = "TFC_Wild_Fire"
author = "HLGOrganization"
version = "v1.0.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ba2d7828134c569a9375f325b117b6f333876f31084e3113f35e54d7452a731"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
