        //戒指属性大致配备如下
        //铜属性相当平庸，青铜提供微量战斗属性，黑铜提供微量魔法属性，铋铜提供探索类属性
        //银提供部分战斗/生命类属性，纹银子进一步提升生命/保温相关
        //金提供最 平均/正常 的全种类属性，玫瑰金提供生命/防御/温度类属性
        //钢提供较强的战斗/防御类型加成，但开始有一定负面效果
        //锰钢的负面效果最剧烈，但提供的战斗属性也很集中
        //玩家可以制作最高锰钢等级的戒指，在结构内能找到部分铜-金时期的戒指
        //普通戒指可以直接打造，华丽/宝石戒指部分偏向于魔法线路，越高级的戒指合成方式越困难
        //e.g. : 锰钢红宝石戒指需要法术线的工作台/对宝石进行注魔合成
        //       铜宝石戒指可以简单的锻造进行镶嵌

StartupEvents.registry('item', event => {
        //戒指指环蓝板
        event.create('shiny_ornaments:copper_ring_base')
        .texture('kubejs:item/copper_ring_base')
        event.create('shiny_ornaments:bronze_ring_base')
        .texture('kubejs:item/bronze_ring_base')
        event.create('shiny_ornaments:bismuth_bronze_ring_base')
        .texture('kubejs:item/bismuth_bronze_ring_base')
        event.create('shiny_ornaments:black_bronze_ring_base')
        .texture('kubejs:item/black_bronze_ring_base')
        event.create('shiny_ornaments:silver_ring_base')
        .texture('kubejs:item/silver_ring_base')
        event.create('shiny_ornaments:sterling_silver_ring_base')
        .texture('kubejs:item/sterling_silver_ring_base')
        event.create('shiny_ornaments:gold_ring_base')
        .texture('kubejs:item/gold_ring_base')
        event.create('shiny_ornaments:rose_gold_ring_base')
        .texture('kubejs:item/rose_gold_ring_base')
        event.create('shiny_ornaments:steel_ring_base')
        .texture('kubejs:item/steel_ring_base')
        event.create('shiny_ornaments:black_steel_ring_base')
        .texture('kubejs:item/black_steel_ring_base')
        //普通戒指
        event.create('shiny_ornaments:copper_ring')
        .texture('kubejs:item/copper_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.armor", "generic.armor", 2, "addition")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:black_bronze_ring')
        .texture('kubejs:item/black_bronze_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_resist", "spell_resist", 0.03, "multiply_total")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:bronze_ring')
        .texture('kubejs:item/bronze_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.knockback_resistance", "generic.knockback_resistance", 0.5, "addition")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:bismuth_bronze_ring')
        .texture('kubejs:item/bismuth_bronze_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:equip_load_max", "equip_load_max", 100, "addition")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:sterling_silver_ring')
        .texture('kubejs:item/sterling_silver_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:mana_regen", "mana_regen", 0.03, "multiply_total")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:silver_ring')
        .texture('kubejs:item/silver_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("legendarysurvivaloverhaul:cold_resistance", "cold_resistance", 1, "addition")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:gold_ring')
        .texture('kubejs:item/gold_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_power", "spell_power", 0.2, "addition")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:rose_gold_ring')
        .texture('kubejs:item/rose_gold_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:life_regeneration", "life_regeneration", 0.05, "multiply_total")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:steel_ring')
        .texture('kubejs:item/steel_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.attack_damage", "generic.attack_damage", 0.25, "addition")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:black_steel_ring')
        .texture('kubejs:item/black_steel_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:critical_damage", "critical_damage", 0.08, "multiply_total")
        )
        .tag("curios:ring")
        .texture('kubejs:item/black_steel_ring')
        
        //精锻戒指
        event.create('shiny_ornaments:copper_delicacy_ring')
        .texture('kubejs:item/copper_delicacy_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:life_regeneration", "life_regeneration", 0.1, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:thermal_resistance", "thermal_resistance", 1, "addition")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:bronze_delicacy_ring')
        .texture('kubejs:item/bronze_delicacy_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.armor_toughness", "generic.armor_toughness", 2, "addition")
        .modifyAttribute("parcool:max_stamina", "max_stamina", 2, "addition")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:black_bronze_delicacy_ring')
        .texture('kubejs:item/black_bronze_delicacy_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:spell_resist", "spell_resist", 0.05, "multiply_total")
        .modifyAttribute("irons_spellbooks:max_mana", "max_mana", 20, "addition")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:bismuth_bronze_delicacy_ring')
        .texture('kubejs:item/bismuth_bronze_delicacy_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.movement_speed", "generic.movement_speed", 0.05, "multiply_total")
        .modifyAttribute("minecraft:generic.luck", "generic.luck", 1, "addition")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:silver_delicacy_ring')
        .texture('kubejs:item/silver_delicacy_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.attack_speed", "generic.attack_speed", 0.1, "addition")
        .modifyAttribute("irons_spellbooks:holy_spell_power", "holy_spell_power", 0.1, "multiply_total")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:sterling_silver_delicacy_ring')
        .texture('kubejs:item/sterling_silver_delicacy_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:life_regeneration", "life_regeneration", 0.08, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:cold_resistance", "cold_resistance", 1, "addition")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:golden_delicacy_ring')
        .texture('kubejs:item/golden_delicacy_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("irons_spellbooks:cooldown_reduction", "cooldown_reduction", 0.1, "multiply_total")
        .modifyAttribute("irons_spellbooks:max_mana", "max_mana", 25, "addition")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:rose_gold_delicacy_ring')
        .texture('kubejs:item/rose_gold_delicacy_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:life_regeneration", "life_regeneration", 0.1, "multiply_total")
        .modifyAttribute("legendarysurvivaloverhaul:thermal_resistance", "thermal_resistance", 1.5, "addition")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:steel_delicacy_ring')
        .texture('kubejs:item/steel_delicacy_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("minecraft:generic.attack_damage", "attack_damage", 0.1, "multiply_total")
        )
        .tag("curios:ring")
        event.create('shiny_ornaments:black_steel_delicacy_ring')
        .texture('kubejs:item/black_steel_delicacy_ring')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
        .modifyAttribute("more_attributes:life_regeneration", "life_regeneration", -0.15, "multiply_total")
        .modifyAttribute("kubejs:life_steal", "attribute.kubejs.life_steal", 15, "addition")
        )
        .tag("curios:ring")
})