#Hard disable entire modules. Use at your own risk and don't ask for support if you use this. Write modid = false to disable modules
#Sun Aug 31 19:33:35 CST 2025
create=true
farmersdelight=true
functionalstorage=true
handcrafted=true
refurbished_furniture=true
valhelsia_furniture=true
valhelsia_structures=true
