#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Mar 15 13:50:29 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=[\u5149\u5F71-\u65E5\u8680]Eclipse-Shader-Unstable[\u4E0D\u652F\u6301\u517C\u5BB9\u975E\u539F\u7248\u6C34].zip
enableShaders=false
