#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Mar 07 04:18:59 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=[BSL_TFC\u517C\u5BB9]BSL_v10.0
