#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Mar 11 22:27:47 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=[BSL_TFC\u517C\u5BB9]BSL_v10.0
enableShaders=false
