# 
#Nutrient addition ratio for fertilizing fertile farmland
#对肥沃耕地施肥的养分加成倍率
#2.5
#Range: 1.0 ~ 10.0
fertilizerOnFertilizedFarmland = 2.5
# 
#The stove provides the highest temperature .
#火炉提供群峦热源可达到的最高温度
#450.0
#Range: 0.0 ~ 2800.0
heatingTemperature = 450.0

