StartupEvents.registry('block', event => {
    //草药-问荆
        event.create('tfc:crop/horsetail', 'tfc:crop')
        .stages(5)
        .displayName("问荆")
        .noCollision()
        .soundType('crop')
        .hardness(0.5)
        .nutrient('nitrogen')
        .tagBlock('tfc:mineable_with_sharp_tool')
        .model('tfc:blockstates/crop/horsetail')
        .existingProductItem('kubejs:horsetail')
        .seedItem(seed => {
            seed.displayName("问荆种子")
            seed.texture('kubejs:item/horsetail_seeds')
        })
        .deadBlock(deadCrop => {
            deadCrop.displayName("枯萎的问荆")
            deadCrop.tagBlock('tfc:mineable_with_sharp_tool')
            deadCrop.soundType('crop')
        })
       //草药-啤酒花
        event.create('tfc:crop/hops', 'tfc:double_crop')
        .stages(3)
        .requiresStick(true)
        .doubleStages(3)
        .displayName("啤酒花")
        .noCollision()
        .soundType('crop')
        .hardness(0.5)
        .nutrient('phosphorous')
        .tagBlock('tfc:mineable_with_sharp_tool')
        .model('tfc:blockstates/crop/hops')
        .existingProductItem('kubejs:hops')
        .seedItem(seed => {
            seed.displayName("啤酒花种子")
            seed.texture('kubejs:item/hops_seed')
        })
        .deadBlock(deadCrop => {
            deadCrop.displayName("枯萎的啤酒花")
            deadCrop.tagBlock('tfc:mineable_with_sharp_tool')
            deadCrop.soundType('crop')
        })
        //草药-金盏花
        event.create('tfc:crop/marigold', 'tfc:crop')
        .stages(3)
        .displayName("金盏花")
        .noCollision()
        .soundType('crop')
        .hardness(0.5)
        .nutrient('nitrogen')
        .tagBlock('tfc:mineable_with_sharp_tool')
        .model('tfc:blockstates/crop/marigold')
        .existingProductItem('kubejs:marigold')
        .seedItem(seed => {
            seed.displayName("金盏花种子")
            seed.texture('kubejs:item/marigold_seeds')
        })
        .deadBlock(deadCrop => {
            deadCrop.displayName("枯萎的金盏花")
            deadCrop.tagBlock('tfc:mineable_with_sharp_tool')
            deadCrop.soundType('crop')
            deadCrop.model('tfc:blockstates/dead_crop/marigold')
        })
        //草药-延龄草
        event.create('tfc:crop/trillium', 'tfc:crop')
        .stages(3)
        .displayName("延龄草")
        .noCollision()
        .soundType('crop')
        .hardness(0.5)
        .nutrient('nitrogen')
        .tagBlock('tfc:mineable_with_sharp_tool')
        .model('tfc:blockstates/crop/trillium')
        .existingProductItem('kubejs:trillium')
        .seedItem(seed => {
            seed.displayName("延龄草种子")
            seed.texture('kubejs:item/trillium_seeds')
        })
        .deadBlock(deadCrop => {
            deadCrop.displayName("枯萎的延龄草")
            deadCrop.tagBlock('tfc:mineable_with_sharp_tool')
            deadCrop.soundType('crop')
            deadCrop.model('tfc:blockstates/dead_crop/trillium')
        })
        //草药-蓝姜
        event.create('tfc:crop/blue_ginger', 'tfc:crop')
        .stages(5)
        .displayName("蓝姜")
        .noCollision()
        .soundType('crop')
        .hardness(0.5)
        .nutrient('nitrogen')
        .tagBlock('tfc:mineable_with_sharp_tool')
        .model('tfc:blockstates/crop/blue_ginger')
        .existingProductItem('kubejs:blue_ginger')
        .seedItem(seed => {
            seed.displayName("蓝姜")
            seed.texture('kubejs:item/blue_ginger_seeds')
        })
        .deadBlock(deadCrop => {
            deadCrop.displayName("枯萎的蓝姜")
            deadCrop.tagBlock('tfc:mineable_with_sharp_tool')
            deadCrop.soundType('crop')
            deadCrop.model('tfc:blockstates/dead_crop/blue_ginger')
        })
        //草药-杜香
        event.create('tfc:crop/labrador_tea', 'tfc:crop')
        .stages(5)
        .displayName("杜香")
        .noCollision()
        .soundType('crop')
        .hardness(0.5)
        .nutrient('nitrogen')
        .tagBlock('tfc:mineable_with_sharp_tool')
        .model('tfc:blockstates/crop/labrador_tea')
        .existingProductItem('kubejs:labrador_tea')
        .seedItem(seed => {
            seed.displayName("杜香种子")
            seed.texture('kubejs:item/labrador_tea_seeds')
        })
        .deadBlock(deadCrop => {
            deadCrop.displayName("枯萎的杜香")
            deadCrop.tagBlock('tfc:mineable_with_sharp_tool')
            deadCrop.soundType('crop')
            deadCrop.model('tfc:blockstates/dead_crop/labrador_tea')
        })
        //草药-红棕榈
        event.create('tfc:crop/red_palm', 'tfc:double_crop')
        .stages(4)
        .requiresStick(false)
        .doubleStages(4)
        .displayName("红棕榈")
        .noCollision()
        .soundType('crop')
        .hardness(0.5)
        .nutrient('phosphorous')
        .tagBlock('tfc:mineable_with_sharp_tool')
        .model('tfc:blockstates/crop/red_palm')
        .existingProductItem('kubejs:palm_heart')
        .seedItem(seed => {
            seed.displayName("红棕榈种子")
            seed.texture('kubejs:item/red_palm_seeds')
        })
        .deadBlock(deadCrop => {
            deadCrop.displayName("枯萎的红棕榈")
            deadCrop.tagBlock('tfc:mineable_with_sharp_tool')
            deadCrop.soundType('crop')
        })

    //作物-肉芽菜
        event.create('tfc:crop/muscle', 'tfc:crop')
        .stages(5)
        .displayName("肌肉")
        .noCollision()
        .soundType('slime_block')
        .hardness(0.9)
        .nutrient('phosphorous')
        .tagBlock('tfc:mineable_with_sharp_tool')
        .model('tfc:blockstates/crop/muscle')
        .existingProductItem('minecraft:beef')
        .seedItem(seed => {
            seed.displayName("肉孢子")
            seed.texture('kubejs:item/granulaspore')
        })
        .deadBlock(deadCrop => {
            deadCrop.displayName("腐烂的肌肉")
            deadCrop.tagBlock('tfc:mineable_with_sharp_tool')
            deadCrop.soundType('slime_block')
        })
})